<?php
$z[0]=Array("global","\r\n                    \$a=\"\r\n                    <li class='col-5-1 last not-animated' data-animate='fadeInUp'>\";\r\n                      \$b=\"\r\n                    \r\n                    <li class='col-5-1 not-animated' data-animate='fadeInUp'>\";\r\n                      if ((@me%5)==0 && @me!=20)  @me=\$a;\r\n                      else  @me=\$b;\r\n                      ",0,420);
$z[0][4]=array();
$z[0][4]['runphp']="yes";
$z[0][4]['name']="autoindex";
$z[1]=Array("arcurl","",475,490);
$z[1][4]=array();
$z[2]=Array("picname","",512,528);
$z[2][4]=array();
$z[3]=Array("title","",535,549);
$z[3][4]=array();

?>