<?php
$z[0]=Array("global","\r\n                    \$a=\"\r\n                    <li class='col-4-1 last not-animated' data-animate='fadeInUp'>\";\r\n                      \$b=\"\r\n                    \r\n                    <li class='col-4-1 not-animated' data-animate='fadeInUp'>\";\r\n                      if ((@me%4)==0 && @me!=10)  @me=\$a;\r\n                      else  @me=\$b;\r\n                      ",0,420);
$z[0][4]=array();
$z[0][4]['runphp']="yes";
$z[0][4]['name']="autoindex";
$z[1]=Array("arcurl","",480,495);
$z[1][4]=array();
$z[2]=Array("picname","",523,539);
$z[2][4]=array();
$z[3]=Array("arcurl","",652,667);
$z[3][4]=array();
$z[4]=Array("title","",685,699);
$z[4][4]=array();
$z[5]=Array("zhiwei","",886,902);
$z[5][4]=array();

?>