<?php
$z[0]=Array("field","",205,263);
$z[0][4]=array();
$z[0][4]['name']="typeid";
$z[0][4]['function']="GetTopTypename(@me)";
$z[1]=Array("channel","\r\n        <li class=\"\"><a href=\"[field:typelink/]\" target=\"\">[field:typename/]</a><i></i></li>\r\n        ",370,621);
$z[1][4]=array();
$z[1][4]['type']="son";
$z[1][4]['currentstyle']="<li class='current'><a href='~typelink~' >~typename~</a><i></i></li>";

?>