<?php  exit();
/*
Page: /dede/makehtml_homepage.php?dopost=view&templet=default/index.htm
Error: Unknown column 'addf.zhiwei' in 'field list' <br />Error sql: <font color='red'>SELECT arc.*,tp.typedir,tp.typename,tp.corank,tp.isdefault,tp.defaultname,tp.namerule,
        tp.namerule2,tp.ispart,tp.moresite,tp.siteurl,tp.sitepath
        ,addf.zhiwei
        FROM `dede_archives` arc LEFT JOIN `dede_arctype` tp on arc.typeid=tp.id
         LEFT JOIN `dede_addonarticle` addf ON addf.aid = arc.id 
         WHERE  arc.typeid IN (20) And  arc.channel = '1'  And  arc.arcrank > -1    ORDER BY arc.sortrank desc  LIMIT 0,4 </font>
Time2018-05-17 11:26:08
*/
?>
<?php  exit();
/*
Page: /dede/makehtml_homepage.php?dopost=view&templet=default/index.htm
Error: Unknown column 'addf.zhiwei' in 'field list' <br />Error sql: <font color='red'>SELECT arc.*,tp.typedir,tp.typename,tp.corank,tp.isdefault,tp.defaultname,tp.namerule,
        tp.namerule2,tp.ispart,tp.moresite,tp.siteurl,tp.sitepath
        ,addf.zhiwei
        FROM `dede_archives` arc LEFT JOIN `dede_arctype` tp on arc.typeid=tp.id
         LEFT JOIN `dede_addonarticle` addf ON addf.aid = arc.id 
         WHERE  arc.typeid IN (20) And  arc.channel = '1'  And  arc.arcrank > -1    ORDER BY arc.sortrank desc  LIMIT 0,4 </font>
Time2018-05-17 11:29:36
*/
?>
<?php  exit();
/*
Page: /
Error: Unknown column 'addf.zhiwei' in 'field list' <br />Error sql: <font color='red'>SELECT arc.*,tp.typedir,tp.typename,tp.corank,tp.isdefault,tp.defaultname,tp.namerule,
        tp.namerule2,tp.ispart,tp.moresite,tp.siteurl,tp.sitepath
        ,addf.zhiwei
        FROM `dede_archives` arc LEFT JOIN `dede_arctype` tp on arc.typeid=tp.id
         LEFT JOIN `dede_addonarticle` addf ON addf.aid = arc.id 
         WHERE  arc.typeid IN (20) And  arc.channel = '1'  And  arc.arcrank > -1    ORDER BY arc.sortrank desc  LIMIT 0,4 </font>
Time2018-05-17 11:50:34
*/
?>
<?php  exit();
/*
Page: /index.php?upcache=1
Error: Unknown column 'addf.zhiwei' in 'field list' <br />Error sql: <font color='red'>SELECT arc.*,tp.typedir,tp.typename,tp.corank,tp.isdefault,tp.defaultname,tp.namerule,
        tp.namerule2,tp.ispart,tp.moresite,tp.siteurl,tp.sitepath
        ,addf.zhiwei
        FROM `dede_archives` arc LEFT JOIN `dede_arctype` tp on arc.typeid=tp.id
         LEFT JOIN `dede_addonarticle` addf ON addf.aid = arc.id 
         WHERE  arc.typeid IN (20) And  arc.channel = '1'  And  arc.arcrank > -1    ORDER BY arc.sortrank desc  LIMIT 0,4 </font>
Time2018-05-18 19:29:04
*/
?>
<?php  exit();
/*
Page: /index.php?upcache=1
Error: Unknown column 'addf.zhiwei' in 'field list' <br />Error sql: <font color='red'>SELECT arc.*,tp.typedir,tp.typename,tp.corank,tp.isdefault,tp.defaultname,tp.namerule,
        tp.namerule2,tp.ispart,tp.moresite,tp.siteurl,tp.sitepath
        ,addf.zhiwei
        FROM `dede_archives` arc LEFT JOIN `dede_arctype` tp on arc.typeid=tp.id
         LEFT JOIN `dede_addonarticle` addf ON addf.aid = arc.id 
         WHERE  arc.typeid IN (20) And  arc.channel = '1'  And  arc.arcrank > -1    ORDER BY arc.sortrank desc  LIMIT 0,4 </font>
Time2018-05-18 19:31:07
*/
?>
<?php  exit();
/*
Page: /index.php?upcache=1
Error: Unknown column 'addf.zhiwei' in 'field list' <br />Error sql: <font color='red'>SELECT arc.*,tp.typedir,tp.typename,tp.corank,tp.isdefault,tp.defaultname,tp.namerule,
        tp.namerule2,tp.ispart,tp.moresite,tp.siteurl,tp.sitepath
        ,addf.zhiwei
        FROM `dede_archives` arc LEFT JOIN `dede_arctype` tp on arc.typeid=tp.id
         LEFT JOIN `dede_addonarticle` addf ON addf.aid = arc.id 
         WHERE  arc.typeid IN (20) And  arc.channel = '1'  And  arc.arcrank > -1    ORDER BY arc.sortrank desc  LIMIT 0,4 </font>
Time2018-05-18 19:31:09
*/
?>
<?php  exit();
/*
Page: /index.php?upcache=1
Error: Unknown column 'addf.zhiwei' in 'field list' <br />Error sql: <font color='red'>SELECT arc.*,tp.typedir,tp.typename,tp.corank,tp.isdefault,tp.defaultname,tp.namerule,
        tp.namerule2,tp.ispart,tp.moresite,tp.siteurl,tp.sitepath
        ,addf.zhiwei
        FROM `dede_archives` arc LEFT JOIN `dede_arctype` tp on arc.typeid=tp.id
         LEFT JOIN `dede_addonarticle` addf ON addf.aid = arc.id 
         WHERE  arc.typeid IN (20) And  arc.channel = '1'  And  arc.arcrank > -1    ORDER BY arc.sortrank desc  LIMIT 0,4 </font>
Time2018-05-18 19:54:22
*/
?>
<?php  exit();
/*
Page: /index.php?upcache=1
Error: Unknown column 'addf.zhiwei' in 'field list' <br />Error sql: <font color='red'>SELECT arc.*,tp.typedir,tp.typename,tp.corank,tp.isdefault,tp.defaultname,tp.namerule,
        tp.namerule2,tp.ispart,tp.moresite,tp.siteurl,tp.sitepath
        ,addf.zhiwei
        FROM `dede_archives` arc LEFT JOIN `dede_arctype` tp on arc.typeid=tp.id
         LEFT JOIN `dede_addonarticle` addf ON addf.aid = arc.id 
         WHERE  arc.typeid IN (20) And  arc.channel = '1'  And  arc.arcrank > -1    ORDER BY arc.sortrank desc  LIMIT 0,4 </font>
Time2018-05-18 20:10:10
*/
?>
<?php  exit();
/*
Page: /index.php?upcache=1
Error: Unknown column 'addf.zhiwei' in 'field list' <br />Error sql: <font color='red'>SELECT arc.*,tp.typedir,tp.typename,tp.corank,tp.isdefault,tp.defaultname,tp.namerule,
        tp.namerule2,tp.ispart,tp.moresite,tp.siteurl,tp.sitepath
        ,addf.zhiwei
        FROM `dede_archives` arc LEFT JOIN `dede_arctype` tp on arc.typeid=tp.id
         LEFT JOIN `dede_addonarticle` addf ON addf.aid = arc.id 
         WHERE  arc.typeid IN (20) And  arc.channel = '1'  And  arc.arcrank > -1    ORDER BY arc.sortrank desc  LIMIT 0,4 </font>
Time2018-05-18 20:28:32
*/
?>
<?php  exit();
/*
Page: /index.php?upcache=1
Error: Unknown column 'addf.zhiwei' in 'field list' <br />Error sql: <font color='red'>SELECT arc.*,tp.typedir,tp.typename,tp.corank,tp.isdefault,tp.defaultname,tp.namerule,
        tp.namerule2,tp.ispart,tp.moresite,tp.siteurl,tp.sitepath
        ,addf.zhiwei
        FROM `dede_archives` arc LEFT JOIN `dede_arctype` tp on arc.typeid=tp.id
         LEFT JOIN `dede_addonarticle` addf ON addf.aid = arc.id 
         WHERE  arc.typeid IN (20) And  arc.channel = '1'  And  arc.arcrank > -1    ORDER BY arc.sortrank desc  LIMIT 0,4 </font>
Time2018-05-18 20:28:32
*/
?>
<?php  exit();
/*
Page: /index.php?upcache=1
Error: Unknown column 'addf.zhiwei' in 'field list' <br />Error sql: <font color='red'>SELECT arc.*,tp.typedir,tp.typename,tp.corank,tp.isdefault,tp.defaultname,tp.namerule,
        tp.namerule2,tp.ispart,tp.moresite,tp.siteurl,tp.sitepath
        ,addf.zhiwei
        FROM `dede_archives` arc LEFT JOIN `dede_arctype` tp on arc.typeid=tp.id
         LEFT JOIN `dede_addonarticle` addf ON addf.aid = arc.id 
         WHERE  arc.typeid IN (20) And  arc.channel = '1'  And  arc.arcrank > -1    ORDER BY arc.sortrank desc  LIMIT 0,4 </font>
Time2018-05-18 20:28:40
*/
?>
<?php  exit();
/*
Page: /index.php?upcache=1
Error: Unknown column 'addf.zhiwei' in 'field list' <br />Error sql: <font color='red'>SELECT arc.*,tp.typedir,tp.typename,tp.corank,tp.isdefault,tp.defaultname,tp.namerule,
        tp.namerule2,tp.ispart,tp.moresite,tp.siteurl,tp.sitepath
        ,addf.zhiwei
        FROM `dede_archives` arc LEFT JOIN `dede_arctype` tp on arc.typeid=tp.id
         LEFT JOIN `dede_addonarticle` addf ON addf.aid = arc.id 
         WHERE  arc.typeid IN (20) And  arc.channel = '1'  And  arc.arcrank > -1    ORDER BY arc.sortrank desc  LIMIT 0,4 </font>
Time2018-05-18 20:56:01
*/
?>
<?php  exit();
/*
Page: /index.php?upcache=1
Error: Unknown column 'addf.zhiwei' in 'field list' <br />Error sql: <font color='red'>SELECT arc.*,tp.typedir,tp.typename,tp.corank,tp.isdefault,tp.defaultname,tp.namerule,
        tp.namerule2,tp.ispart,tp.moresite,tp.siteurl,tp.sitepath
        ,addf.zhiwei
        FROM `dede_archives` arc LEFT JOIN `dede_arctype` tp on arc.typeid=tp.id
         LEFT JOIN `dede_addonarticle` addf ON addf.aid = arc.id 
         WHERE  arc.typeid IN (20) And  arc.channel = '1'  And  arc.arcrank > -1    ORDER BY arc.sortrank desc  LIMIT 0,4 </font>
Time2018-05-18 20:56:23
*/
?>
<?php  exit();
/*
Page: /index.php?upcache=1
Error: Unknown column 'addf.zhiwei' in 'field list' <br />Error sql: <font color='red'>SELECT arc.*,tp.typedir,tp.typename,tp.corank,tp.isdefault,tp.defaultname,tp.namerule,
        tp.namerule2,tp.ispart,tp.moresite,tp.siteurl,tp.sitepath
        ,addf.zhiwei
        FROM `dede_archives` arc LEFT JOIN `dede_arctype` tp on arc.typeid=tp.id
         LEFT JOIN `dede_addonarticle` addf ON addf.aid = arc.id 
         WHERE  arc.typeid IN (20) And  arc.channel = '1'  And  arc.arcrank > -1    ORDER BY arc.sortrank desc  LIMIT 0,4 </font>
Time2018-05-21 18:38:41
*/
?>
